### PR TITLE
Update cross-document docs page

### PR DESCRIPTION
**Pull request by mattjennings**
- add examples to each xdoc message
- add documentation for interceptRequest and interceptResponse

This also changes the formatting to use headers for each message type, but i'm not sure how it'll look in gitbook since I made the changes via markdown. Ideally it'll look good and it will have each message in the table of contents.

### CODE REVIEW

**Comment by weiyin** [comment]
@mattjennings Deployed. Looks decent to me, what do you think? https://docs.appetize.io/core-features/cross-document-messages

**Comment by mattjennings** [comment]
I think that looks okay. It's too bad it doesn't have syntax highlighting and has line numbers, maybe that's configurable?

**Comment by weiyin** [comment]
@mattjennings I think it will work if we denote the blocks with 

    ```typescript instead of
    ```ts

**Comment by mattjennings** [comment]
@weiyin opened #5 to see if that does the trick

**Pull request merged**
